runtime: python27

instance_class: F2

env_variables:
  BUCKET_NAME: "ornate-justice-381214.appspot.com"

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  
- url: /images
  static_dir: static/images

- url: /(.*)
    static_files: www/\1
    upload: www/(.*)
  
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
